echo mkpvdirs
if not exist %1\dist mkdir %1\dist

if not exist %1\dist\sign mkdir %1\dist\sign
if not exist %1\dist\prev_sign mkdir %1\dist\prev_sign

if not exist %1\dist\sign\sys mkdir %1\dist\sign\sys
if not exist %1\dist\sign\sys\w2k-32fre mkdir %1\dist\sign\sys\w2k-32fre
if not exist %1\dist\sign\sys\w2k-32chk mkdir %1\dist\sign\sys\w2k-32chk
if not exist %1\dist\sign\sys\wxp-32fre mkdir %1\dist\sign\sys\wxp-32fre
if not exist %1\dist\sign\sys\wxp-32chk mkdir %1\dist\sign\sys\wxp-32chk
if not exist %1\dist\sign\sys\w2k3-32fre mkdir %1\dist\sign\sys\w2k3-32fre
if not exist %1\dist\sign\sys\w2k3-32chk mkdir %1\dist\sign\sys\w2k3-32chk
if not exist %1\dist\sign\sys\w2k3-64fre mkdir %1\dist\sign\sys\w2k3-64fre
if not exist %1\dist\sign\sys\w2k3-64chk mkdir %1\dist\sign\sys\w2k3-64chk
if not exist %1\dist\sign\sys\w2k8-32fre mkdir %1\dist\sign\sys\w2k8-32fre
if not exist %1\dist\sign\sys\w2k8-32chk mkdir %1\dist\sign\sys\w2k8-32chk
if not exist %1\dist\sign\sys\w2k8-64fre mkdir %1\dist\sign\sys\w2k8-64fre
if not exist %1\dist\sign\sys\w2k8-64chk mkdir %1\dist\sign\sys\w2k8-64chk

if not exist %1\dist\sign\cat mkdir %1\dist\sign\cat
if not exist %1\dist\sign\cat\w2k-32fre mkdir %1\dist\sign\cat\w2k-32fre
if not exist %1\dist\sign\cat\w2k-32chk mkdir %1\dist\sign\cat\w2k-32chk
if not exist %1\dist\sign\cat\wxp-32fre mkdir %1\dist\sign\cat\wxp-32fre
if not exist %1\dist\sign\cat\wxp-32chk mkdir %1\dist\sign\cat\wxp-32chk
if not exist %1\dist\sign\cat\w2k3-32fre mkdir %1\dist\sign\cat\w2k3-32fre
if not exist %1\dist\sign\cat\w2k3-32chk mkdir %1\dist\sign\cat\w2k3-32chk
if not exist %1\dist\sign\cat\w2k3-64fre mkdir %1\dist\sign\cat\w2k3-64fre
if not exist %1\dist\sign\cat\w2k3-64chk mkdir %1\dist\sign\cat\w2k3-64chk
if not exist %1\dist\sign\cat\w2k8-32fre mkdir %1\dist\sign\cat\w2k8-32fre
if not exist %1\dist\sign\cat\w2k8-32chk mkdir %1\dist\sign\cat\w2k8-32chk
if not exist %1\dist\sign\cat\w2k8-64fre mkdir %1\dist\sign\cat\w2k8-64fre
if not exist %1\dist\sign\cat\w2k8-64chk mkdir %1\dist\sign\cat\w2k8-64chk

if not exist %1\dist\sign\exe mkdir %1\dist\sign\exe
if not exist %1\dist\sign\exe\main-fre mkdir %1\dist\sign\exe\main-fre
if not exist %1\dist\sign\exe\main-chk mkdir %1\dist\sign\exe\main-chk
if not exist %1\dist\sign\exe\w2k-32fre mkdir %1\dist\sign\exe\w2k-32fre
if not exist %1\dist\sign\exe\w2k-32chk mkdir %1\dist\sign\exe\w2k-32chk
if not exist %1\dist\sign\exe\wxp-32fre mkdir %1\dist\sign\exe\wxp-32fre
if not exist %1\dist\sign\exe\wxp-32chk mkdir %1\dist\sign\exe\wxp-32chk
if not exist %1\dist\sign\exe\w2k3-32fre mkdir %1\dist\sign\exe\w2k3-32fre
if not exist %1\dist\sign\exe\w2k3-32chk mkdir %1\dist\sign\exe\w2k3-32chk
if not exist %1\dist\sign\exe\w2k3-64fre mkdir %1\dist\sign\exe\w2k3-64fre
if not exist %1\dist\sign\exe\w2k3-64chk mkdir %1\dist\sign\exe\w2k3-64chk
if not exist %1\dist\sign\exe\w2k8-32fre mkdir %1\dist\sign\exe\w2k8-32fre
if not exist %1\dist\sign\exe\w2k8-32chk mkdir %1\dist\sign\exe\w2k8-32chk
if not exist %1\dist\sign\exe\w2k8-64fre mkdir %1\dist\sign\exe\w2k8-64fre
if not exist %1\dist\sign\exe\w2k8-64chk mkdir %1\dist\sign\exe\w2k8-64chk

if not exist %1\dist\built mkdir %1\dist\built
if not exist %1\dist\built\eula mkdir %1\dist\built\eula
if not exist %1\dist\built\base mkdir %1\dist\built\base
if not exist %1\dist\built\doc mkdir %1\dist\built\doc
if not exist %1\dist\built\dpinst mkdir %1\dist\built\dpinst
if not exist %1\dist\built\dpinst\x86 mkdir %1\dist\built\dpinst\x86
if not exist %1\dist\built\dpinst\x64 mkdir %1\dist\built\dpinst\x64
if not exist %1\dist\built\cdf mkdir %1\dist\built\cdf
if not exist %1\dist\built\main-fre mkdir %1\dist\built\main-fre
if not exist %1\dist\built\main-chk mkdir %1\dist\built\main-chk
if not exist %1\dist\built\w2k-32fre mkdir %1\dist\built\w2k-32fre
if not exist %1\dist\built\w2k-32chk mkdir %1\dist\built\w2k-32chk
if not exist %1\dist\built\wxp-32fre mkdir %1\dist\built\wxp-32fre
if not exist %1\dist\built\wxp-32chk mkdir %1\dist\built\wxp-32chk
if not exist %1\dist\built\w2k3-32fre mkdir %1\dist\built\w2k3-32fre
if not exist %1\dist\built\w2k3-32chk mkdir %1\dist\built\w2k3-32chk
if not exist %1\dist\built\w2k3-64fre mkdir %1\dist\built\w2k3-64fre
if not exist %1\dist\built\w2k3-64chk mkdir %1\dist\built\w2k3-64chk
if not exist %1\dist\built\w2k8-32fre mkdir %1\dist\built\w2k8-32fre
if not exist %1\dist\built\w2k8-32chk mkdir %1\dist\built\w2k8-32chk
if not exist %1\dist\built\w2k8-64fre mkdir %1\dist\built\w2k8-64fre
if not exist %1\dist\built\w2k8-64chk mkdir %1\dist\built\w2k8-64chk

if not exist %1\dist\vmdp_base mkdir %1\dist\vmdp_base
if not exist %1\dist\vmdp_base\eula mkdir %1\dist\vmdp_base\eula
if not exist %1\dist\vmdp_base\doc mkdir %1\dist\vmdp_base\doc
if not exist %1\dist\vmdp_base\dpinst mkdir %1\dist\vmdp_base\dpinst
if not exist %1\dist\vmdp_base\dpinst\x86 mkdir %1\dist\vmdp_base\dpinst\x86
if not exist %1\dist\vmdp_base\dpinst\x64 mkdir %1\dist\vmdp_base\dpinst\x64
if not exist %1\dist\vmdp_base\cdf mkdir %1\dist\vmdp_base\cdf
if not exist %1\dist\vmdp_base\main-fre mkdir %1\dist\vmdp_base\main-fre
if not exist %1\dist\vmdp_base\main-chk mkdir %1\dist\vmdp_base\main-chk
if not exist %1\dist\vmdp_base\w2k-32fre mkdir %1\dist\vmdp_base\w2k-32fre
if not exist %1\dist\vmdp_base\w2k-32chk mkdir %1\dist\vmdp_base\w2k-32chk
if not exist %1\dist\vmdp_base\wxp-32fre mkdir %1\dist\vmdp_base\wxp-32fre
if not exist %1\dist\vmdp_base\wxp-32chk mkdir %1\dist\vmdp_base\wxp-32chk
if not exist %1\dist\vmdp_base\w2k3-32fre mkdir %1\dist\vmdp_base\w2k3-32fre
if not exist %1\dist\vmdp_base\w2k3-32chk mkdir %1\dist\vmdp_base\w2k3-32chk
if not exist %1\dist\vmdp_base\w2k3-64fre mkdir %1\dist\vmdp_base\w2k3-64fre
if not exist %1\dist\vmdp_base\w2k3-64chk mkdir %1\dist\vmdp_base\w2k3-64chk
if not exist %1\dist\vmdp_base\w2k8-32fre mkdir %1\dist\vmdp_base\w2k8-32fre
if not exist %1\dist\vmdp_base\w2k8-32chk mkdir %1\dist\vmdp_base\w2k8-32chk
if not exist %1\dist\vmdp_base\w2k8-64fre mkdir %1\dist\vmdp_base\w2k8-64fre
if not exist %1\dist\vmdp_base\w2k8-64chk mkdir %1\dist\vmdp_base\w2k8-64chk
