mkdir winpv_stage
mkdir winpv_stage/inf
mkdir winpv_stage/inf/w2k
mkdir winpv_stage/inf/wxp
mkdir winpv_stage/inf/w2k3
mkdir winpv_stage/inf/w2k8
mkdir winpv_stage/w2k-32fre
mkdir winpv_stage/w2k-32chk
mkdir winpv_stage/wxp-32fre
mkdir winpv_stage/wxp-32chk
mkdir winpv_stage/w2k3-32fre
mkdir winpv_stage/w2k3-32chk
mkdir winpv_stage/w2k3-64fre
mkdir winpv_stage/w2k3-64chk
mkdir winpv_stage/w2k8-32fre
mkdir winpv_stage/w2k8-32chk
mkdir winpv_stage/w2k8-64fre
mkdir winpv_stage/w2k8-64chk
