obj-m += shm_signal.o
obj-m += ioq.o

vbus-proxy-objs += bus-proxy.o
obj-m += vbus-proxy.o

vbus-pcibridge-objs += pci-bridge.o
obj-m += vbus-pcibridge.o

obj-m += vbus-enet.o

KVERSION = $(shell uname -r)


